spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testcode
    password: 1184421as!
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
